---
# Setup basic system

- hosts: all
  remote_user: root
  tasks:
      - name: Install ntpdate
        yum:
            name: ntpdate
            state: latest
            update_cache: yes
      - name: Install nano
        yum:
            name: nano
            state: latest
      - name: Install vim
        yum:
            name: vim
            state: latest
#      - name: Add Epel for htop
#        yum:
#            name: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm
#            state: present
#      - name: Install htop
#        yum:
#            name: htop
#            state: present
      - name: Install net tools
        yum:
            name: net-tools
            state: latest
      - name: Install Midnight Commander
        yum:
            name: mc
            state: latest
