---
# Install Java
- name: Install Java
  hosts: all
  remote_user: root
  tasks:
      - name: install Java
        yum:
            name: java-1.8.0-openjdk-headless.x86_64
            state: present
